# Generated by Django 3.2.9 on 2021-12-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category_id',
            new_name='parent_category',
        ),
    ]
