# Generated by Django 3.2.9 on 2021-12-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_parent_category_id_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', unique=True),
        ),
    ]
